[package]
name = "wee_alloc_vec_of_enums_bug"
version = "0.1.0"
authors = ["Mason Fischer <mason@kissr.co>"]

[lib]
crate_type = ["cdylib"]

[dependencies]
wee_alloc = { git = "https://github.com/fitzgen/wee_alloc", default-features = false}
rlibc = "1.0"
